name: Release on PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  release:
    name: Release on Pypi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Make sure to use the correct version here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flit
        run: python -m pip install flit

      - name: Build and Publish
        env:
          # Assuming you have a secret named PYPI_API_TOKEN
          FLIT_AUTH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          flit publish
